
import {
    DollarSign,
    TrendingUp,
    Briefcase,
    Users,
    Repeat,
    FileText,
    Percent,
    UserCheck,
    CalendarCheck,
    Timer,
    HeartHandshake,
    Clock,
    UserSquare,
    Calculator,
    Star,
    Trash2,
    Truck,
    CheckCircle,
    XCircle,
    History,
    FileSignature,
    TrendingDown,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export interface Kpi {
    id: string;
    title: string;
    description: string;
    category: string;
    icon: LucideIcon;
}

export const allKpis: Kpi[] = [
    // Profitability
    { id: 'totalRevenue', title: 'Total Revenue', description: 'Total income from sales before expenses.', category: 'Profitability', icon: TrendingUp },
    { id: 'directExpenses', title: 'Direct Expenses', description: 'Costs directly related to jobs (labor, materials).', category: 'Profitability', icon: TrendingDown },
    { id: 'grossProfit', title: 'Gross Profit', description: 'Revenue minus direct expenses.', category: 'Profitability', icon: DollarSign },
    { id: 'netProfitMargin', title: 'Net Profit Margin', description: '(Net Profit ÷ Total Revenue) × 100.', category: 'Profitability', icon: Percent },

    // Revenue & Conversion
    { id: 'closeRate', title: 'Estimate-to-Close Rate', description: '% of Estimates that convert to Jobs.', category: 'Revenue & Conversion', icon: CheckCircle },
    { id: 'avgInvoiceValue', title: 'Average Invoice Value', description: 'Sum of paid invoices ÷ # of invoices.', category: 'Revenue & Conversion', icon: FileText },
    { id: 'customerLifetimeValue', title: 'Customer Lifetime Value', description: 'Avg. revenue from a customer over their lifespan.', category: 'Revenue & Conversion', icon: HeartHandshake },
    { id: 'recurringRevenue', title: 'Recurring Revenue %', description: 'Income from service agreements.', category: 'Revenue & Conversion', icon: Repeat },

    // Operational Efficiency
    { id: 'firstTimeFixRate', title: 'First-Time Fix Rate', description: '% of jobs completed on the first visit.', category: 'Operational Efficiency', icon: Briefcase },
    { id: 'jobsPerDayPerTech', title: 'Jobs per Day per Technician', description: 'Efficiency of scheduling and routing.', category: 'Operational Efficiency', icon: Users },
    { id: 'repeatCustomerRate', title: 'Repeat Customer Rate', description: '% of customers who’ve booked more than once.', category: 'Operational Efficiency', icon: Repeat },
    { id: 'onTimeArrivalRate', title: 'On-Time Arrival Rate', description: '% of jobs techs arrived on time.', category: 'Operational Efficiency', icon: Timer },
    { id: 'avgJobDuration', title: 'Average Job Duration', description: 'Total time spent ÷ number of jobs.', category: 'Operational Efficiency', icon: Clock },
    { id: 'avgTravelTime', title: 'Travel Time per Job', description: 'Avg. travel time from base to job.', category: 'Operational Efficiency', icon: Truck },

    // Technician Performance
    { id: 'revenuePerTech', title: 'Avg. Revenue per Technician', description: 'Total revenue generated by each tech.', category: 'Technician Performance', icon: UserSquare },
    { id: 'jobsPerTechPerWeek', title: 'Avg. Jobs per Tech per Week', description: 'Good for workload balancing.', category: 'Technician Performance', icon: CalendarCheck },
    { id: 'billableUtilization', title: 'Billable Utilization Rate', description: '(Billable Hours ÷ Total Tech Hours) × 100', category: 'Technician Performance', icon: Percent },
    { id: 'upsellRate', title: 'Upsell/Addon Rate', description: '% of jobs where additional services were sold.', category: 'Technician Performance', icon: TrendingUp },
];
