
import { Customer, Invoice, Job, Technician, UserRole, Equipment, Estimate, EstimateTemplate, PricebookItem, InventoryItem, Payment, ServiceAgreement, Refund, TaxLine, PaymentPlan, Deposit, ChangeOrder, AuditLogEntry, TaxZone, PartRequest, ShoppingListItem, PurchaseOrder, PurchaseOrderPart, EquipmentLog, PartUsageLog, User, Vendor } from './types';

const getDay = (day: number) => {
    const newDate = new Date();
    const currentDay = newDate.getDay();
    const distance = day - currentDay;
    newDate.setDate(newDate.getDate() + distance);
    return newDate;
}

// Wrapping our mock data in a single object makes it mutable across requests
// in a Node.js development server environment. This simulates a persistent store.
export const mockData: { [key: string]: any } = {
  scheduleSettings: {
    startHour: 5,
    endHour: 19,
  },
  vendors: [
    { 
      id: 'vendor_fhd1', 
      name: 'Ferguson Plumbing Supply', 
      contactName: 'Amanda Rivera', 
      phone: '555-123-4567', 
      email: 'arivera@ferguson.com', 
      website: 'ferguson.com', 
      paymentTerms: 'Net 30', 
      createdAt: new Date(), 
      preferred: true, 
      trades: ['Plumbing', 'HVAC'],
      categories: ['Fittings', 'Tools', 'Water Heaters'],
      locations: [
        { address: '456 Warehouse Rd, Dallas, TX', region: 'DFW' },
        { address: '123 Main St, Fort Worth, TX', region: 'Fort Worth' }
      ],
      portalUrl: 'https://www.ferguson.com/',
      deliveryOptions: ['Warehouse'],
      addedBy: 'admin_001'
    },
    { 
      id: 'vendor_js1', 
      name: 'Johnstone Supply', 
      contactName: 'Bill Thompson', 
      phone: '555-987-6543', 
      email: 'bthompson@johnstone.com', 
      website: 'johnstonesupply.com', 
      paymentTerms: 'Net 30', 
      createdAt: new Date(), 
      preferred: true, 
      trades: ['HVAC'],
      categories: ['Capacitors', 'Control Boards', 'Refrigerant'],
      locations: [
        { address: '789 Industrial Blvd, Plano, TX', region: 'DFW' }
      ],
      portalUrl: 'https://www.johnstonesupply.com/',
      deliveryOptions: ['Warehouse', 'Tech Truck'],
      addedBy: 'admin_001'
    },
    { 
      id: 'vendor_rem1', 
      name: 'RE Michel Company', 
      contactName: 'Chris Green', 
      phone: '555-555-1111', 
      email: 'cgreen@remichel.com', 
      website: 'remichel.com', 
      paymentTerms: 'Net 30', 
      createdAt: new Date(), 
      preferred: false, 
      trades: ['HVAC'],
      categories: ['Control Boards', 'Furnace Parts'],
      locations: [],
      portalUrl: 'https://www.remichel.com/',
      deliveryOptions: ['Warehouse'],
      addedBy: 'admin_001'
    },
    { 
      id: 'vendor_hd1', 
      name: 'Home Depot Pro', 
      contactName: 'Pro Desk', 
      phone: '800-466-3337', 
      email: 'pro@homedepot.com', 
      website: 'homedepot.com/pro', 
      paymentTerms: 'Credit Card', 
      createdAt: new Date(), 
      preferred: false, 
      trades: ['Plumbing', 'Electrical', 'General'],
      categories: ['Outlets', 'Tools', 'General Supplies'],
      locations: [
         { address: '111 W Carpenter Fwy, Irving, TX', region: 'DFW' }
      ],
      portalUrl: 'https://www.homedepot.com/c/pro',
      deliveryOptions: ['Tech Truck'],
      addedBy: 'admin_001'
    },
  ] as Vendor[],
  users: [
      { id: 'admin1', name: 'Admin User', email: 'admin@servicerig.com', role: UserRole.Admin, active: true },
      { id: 'dispatch1', name: 'Dispatcher Dan', email: 'dan@servicerig.com', role: UserRole.Dispatcher, active: true },
      { id: 'tech1', name: 'John Doe', email: 'john@servicerig.com', role: UserRole.Technician, active: true, color: 'hsl(210 80% 80%)' },
      { id: 'tech2', name: 'Jane Smith', email: 'jane@servicerig.com', role: UserRole.Technician, active: true, color: 'hsl(150 80% 80%)' },
      { id: 'tech3', name: 'Mike Johnson', email: 'mike@servicerig.com', role: UserRole.Technician, active: true, color: 'hsl(40 80% 80%)' },
      { id: 'tech4', name: 'Emily Brown', email: 'emily@servicerig.com', role: UserRole.Technician, active: false, color: 'hsl(300 80% 80%)' },
  ] as User[],
  partUsageLogs: [
      { id: 'pulog1', partId: 'inv_part_001', quantity: 1, timestamp: new Date(new Date().setDate(new Date().getDate() - 1)), technicianId: 'tech1', jobId: 'job1' },
      { id: 'pulog2', partId: 'inv_part_003', quantity: 2, timestamp: new Date(new Date().setDate(new Date().getDate() - 1)), technicianId: 'tech1', jobId: 'job1' },
      { id: 'pulog3', partId: 'inv_part_002', quantity: 1, timestamp: new Date(new Date().setDate(new Date().getDate() - 2)), technicianId: 'tech2', jobId: 'job2' },
      { id: 'pulog4', partId: 'inv_part_001', quantity: 1, timestamp: new Date(new Date().setDate(new Date().getDate() - 3)), technicianId: 'tech1', jobId: 'job3' },
      { id: 'pulog5', partId: 'inv_part_005', quantity: 1, timestamp: new Date(new Date().setDate(new Date().getDate() - 3)), technicianId: 'tech1', jobId: 'job3' },
      { id: 'pulog6', partId: 'inv_part_001', quantity: 1, timestamp: new Date(new Date().setDate(new Date().getDate() - 4)), technicianId: 'tech2', jobId: 'job4' },
      { id: 'pulog7', partId: 'inv_part_004', quantity: 1, timestamp: new Date(new Date().setDate(new Date().getDate() - 10)), technicianId: 'tech2', jobId: 'job2' },
  ] as PartUsageLog[],
  equipmentLogs: [
    { id: 'log_equip1_1', equipmentId: 'equip1', timestamp: new Date(new Date().setDate(new Date().getDate() - 10)), type: 'inspection', technicianId: 'tech1', notes: 'Passed annual inspection. All functions normal.' },
    { id: 'log_equip1_2', equipmentId: 'equip1', timestamp: new Date(new Date().setDate(new Date().getDate() - 5)), type: 'usage', technicianId: 'tech1', notes: 'Used on job1 for diagnostics.' },
    { id: 'log_equip2_1', equipmentId: 'equip2', timestamp: new Date(new Date().setDate(new Date().getDate() - 3)), type: 'repair', technicianId: 'tech2', notes: 'Replaced faulty pressure gauge. Tested OK.' },
    { id: 'log_equip3_1', equipmentId: 'equip3', timestamp: new Date(new Date().setDate(new Date().getDate() - 1)), type: 'note', technicianId: 'admin1', notes: 'Assigned to Jane Smith.' },
  ] as EquipmentLog[],
  purchaseOrders: [
    {
        id: 'po1',
        vendorId: 'vendor_js1',
        vendor: 'Johnstone Supply',
        parts: [{ partId: 'inv_part_001', qty: 20, unitCost: 12.50 }],
        total: 250,
        status: 'ordered',
        destination: 'Warehouse',
        orderDate: new Date(new Date().setDate(new Date().getDate() - 5)),
        expectedDeliveryDate: new Date(new Date().setDate(new Date().getDate() + 2)),
        createdAt: new Date(),
        updatedAt: new Date(),
        requestedBy: 'Admin User'
    },
    {
        id: 'po2',
        vendorId: 'vendor_fhd1',
        vendor: 'Ferguson',
        parts: [
            { partId: 'inv_part_002', qty: 10, unitCost: 45.00 },
            { partId: 'inv_part_004', qty: 5, unitCost: 95.00 },
        ],
        total: 925,
        status: 'received',
        destination: 'Warehouse',
        orderDate: new Date(new Date().setDate(new Date().getDate() - 10)),
        expectedDeliveryDate: new Date(new Date().setDate(new Date().getDate() - 3)),
        createdAt: new Date(),
        updatedAt: new Date(),
        requestedBy: 'Admin User',
        receivedBy: 'admin1',
        receivedAt: new Date(new Date().setDate(new Date().getDate() - 3)),
        deliveryNotes: 'All items received in good condition.'
    },
    {
        id: 'po_field_1',
        vendorId: 'vendor_hd1',
        vendor: 'Home Depot',
        parts: [{ partId: 'inv_part_003', qty: 5, unitCost: 18.50 }],
        total: 92.50,
        status: 'field-purchased',
        destination: 'tech1',
        orderDate: new Date(new Date().setDate(new Date().getDate() - 1)),
        isFieldPurchase: true,
        jobId: 'job1',
        receiptImage: 'https://placehold.co/400x600.png',
        createdAt: new Date(),
        updatedAt: new Date(),
        requestedBy: 'John Doe',
        receivedBy: 'tech1',
        receivedAt: new Date(new Date().setDate(new Date().getDate() - 1)),
    },
    {
        id: 'po3',
        vendorId: 'vendor_rem1',
        vendor: 'RE Michel',
        parts: [{ partId: 'inv_part_005', qty: 4, unitCost: 85.00 }],
        total: 340,
        status: 'pending',
        destination: 'tech2',
        orderDate: new Date(new Date().setDate(new Date().getDate() - 2)),
        expectedDeliveryDate: new Date(new Date().setDate(new Date().getDate() + 5)),
        createdAt: new Date(),
        updatedAt: new Date(),
        requestedBy: 'Jane Smith'
    },
  ] as PurchaseOrder[],
  shoppingList: [] as ShoppingListItem[],
  partRequests: [
    { id: 'req1', technicianId: 'tech1', technicianName: 'John Doe', itemName: 'Something for the job', quantity: 1, status: 'pending', createdAt: new Date(new Date().setDate(new Date().getDate() - 1)) },
    { id: 'req2', technicianId: 'tech1', technicianName: 'John Doe', itemId: 'inv_part_004', itemName: 'Standard 1-Handle Faucet', quantity: 1, status: 'fulfilled', jobId: 'job2', createdAt: new Date(new Date().setDate(new Date().getDate() - 5)), fulfilledAt: new Date(new Date().setDate(new Date().getDate() - 4))},
    { id: 'req3', technicianId: 'tech2', technicianName: 'Jane Smith', itemName: 'Universal Ignitor', quantity: 2, status: 'pending', createdAt: new Date() },
  ] as PartRequest[],
  taxZones: [
    { id: 'ca-sv', name: 'California (Silicon Valley)', rate: 0.0925 },
    { id: 'il-metro', name: 'Illinois (Metropolis)', rate: 0.08 },
    { id: 'ny-gotham', name: 'New York (Gotham)', rate: 0.08875 },
    { id: 'no-tax', name: 'No Tax', rate: 0 },
  ] as TaxZone[],
  changeOrders: [
    {
      id: 'co1',
      jobId: 'job1',
      customerId: 'cust1',
      title: 'Upgrade to Smart Thermostat',
      description: 'Customer requested an upgrade from the standard thermostat to a Nest Smart Thermostat.',
      lineItems: [
        { description: 'Nest Learning Thermostat', quantity: 1, unitPrice: 249.00 },
        { description: 'Additional Labor for Setup', quantity: 1, unitPrice: 75.00 },
      ],
      total: 324.00,
      status: 'approved',
      createdAt: new Date('2024-07-10T11:00:00Z'),
      updatedAt: new Date('2024-07-10T11:30:00Z'),
    },
    {
      id: 'co2',
      jobId: 'job2',
      customerId: 'cust2',
      title: 'Additional Outlet Installation',
      description: 'While on site, customer requested an additional GFCI outlet to be installed by the sink.',
       lineItems: [
        { description: '15 Amp GFCI Outlet', quantity: 1, unitPrice: 28.00 },
        { description: 'Labor for new outlet', quantity: 1, unitPrice: 120.00 },
      ],
      total: 148.00,
      status: 'invoiced',
      createdAt: new Date('2024-06-01T11:00:00Z'),
      updatedAt: new Date('2024-06-01T11:30:00Z'),
    }
  ] as ChangeOrder[],
  deposits: [
    { id: 'dep1', customerId: 'cust2', amount: 500.00, status: 'available', createdAt: new Date('2024-07-01'), originalInvoiceId: 'inv_dep_123' },
  ] as Deposit[],
  refunds: [
    { id: 'ref1', invoiceId: 'inv1', amount: 50.00, date: new Date('2024-07-16'), method: 'original_payment', reason: 'Goodwill gesture for delay', processedBy: 'user_admin_01' }
  ] as Refund[],
  serviceAgreements: [
    {
        id: 'sa1',
        title: 'Innovate Inc. HVAC Platinum Plan',
        customerId: 'cust1',
        status: 'active',
        billingSchedule: { frequency: 'quarterly', nextDueDate: new Date(new Date().getFullYear(), new Date().getMonth() + 1, 1) },
        autoInvoiceEnabled: true,
        startDate: new Date('2023-01-01'),
        linkedJobIds: [],
        amount: 500,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 'sa2',
        title: 'Solutions Corp. Monthly Maintenance',
        customerId: 'cust2',
        status: 'active',
        billingSchedule: { frequency: 'monthly', nextDueDate: new Date(new Date().getFullYear(), new Date().getMonth(), 20) },
        autoInvoiceEnabled: false,
        startDate: new Date('2024-03-01'),
        linkedJobIds: [],
        amount: 250,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
     {
        id: 'sa3',
        title: 'Gadgets & More Annual Checkup',
        customerId: 'cust3',
        status: 'cancelled',
        billingSchedule: { frequency: 'annually', nextDueDate: new Date('2025-01-15') },
        autoInvoiceEnabled: true,
        startDate: new Date('2023-01-15'),
        endDate: new Date('2024-01-14'),
        linkedJobIds: [],
        amount: 800,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
  ] as ServiceAgreement[],
  payments: [
    { id: 'pay1', invoiceId: 'inv1', customerId: 'cust1', amount: 324.00, date: new Date('2024-07-15'), method: 'Credit Card', transactionId: 'ch_12345', recordedBy: 'user_admin_01' },
    { id: 'pay2', invoiceId: 'inv2', customerId: 'cust2', amount: 400.00, date: new Date('2024-07-05'), method: 'Check', transactionId: 'check_1054', recordedBy: 'user_admin_01' },
    { id: 'pay3', invoiceId: 'inv3', customerId: 'cust3', amount: 108.00, date: new Date('2024-07-20'), method: 'Credit Card', transactionId: 'ch_67890', recordedBy: 'user_admin_01' },
  ] as Payment[],
  inventoryItems: [
    { id: 'inv_part_001', name: 'Dual-run Capacitor 45/5 MFD', description: 'Oval run capacitor for HVAC condenser units.', sku: 'CAP-45-5', partNumber: 'PRCFD455A', modelNumber: 'CBB65', vendor: 'Johnstone Supply', category: 'Capacitors', trade: 'HVAC', quantityOnHand: 50, reorderThreshold: 10, reorderQtyDefault: 20, warehouseLocation: 'Aisle 3, Bin 4', unitCost: 12.50, ourPrice: 35.00, truckLocations: [{technicianId: 'tech1', quantity: 5}] , createdAt: new Date() },
    { id: 'inv_part_002', name: '1/2" PEX-A Pipe (100ft)', description: 'Uponor PEX-A pipe for plumbing.', sku: 'PEX-A-050-100', partNumber: 'F1040500', modelNumber: 'AquaPEX', vendor: 'Ferguson', category: 'Piping', trade: 'Plumbing', quantityOnHand: 2, reorderThreshold: 5, reorderQtyDefault: 10, warehouseLocation: 'Aisle 1, Bay 2', unitCost: 45.00, ourPrice: 75.00, truckLocations: [], createdAt: new Date() },
    { id: 'inv_part_003', name: '15 Amp GFCI Outlet', description: 'Leviton GFCI duplex receptacle, white.', sku: 'ELEC-GFCI-15A', partNumber: 'GFTR1-W', modelNumber: 'GFTR1', vendor: 'Home Depot Pro', category: 'Outlets', trade: 'Electrical', quantityOnHand: 150, reorderThreshold: 25, reorderQtyDefault: 50, warehouseLocation: 'Aisle 5, Bin 12', unitCost: 15.00, ourPrice: 28.00, truckLocations: [{technicianId: 'tech1', quantity: 10}, {technicianId: 'tech2', quantity: 8}], createdAt: new Date() },
    { id: 'inv_part_004', name: 'Standard 1-Handle Faucet', description: 'Moen chrome single handle kitchen faucet.', sku: 'FAUC-K-MOEN-1H', partNumber: '7425', modelNumber: '7400 Series', vendor: 'Ferguson', category: 'Faucets', trade: 'Plumbing', quantityOnHand: 15, reorderThreshold: 5, reorderQtyDefault: 5, warehouseLocation: 'Aisle 1, Bin 6', unitCost: 95.00, ourPrice: 165.00, truckLocations: [], createdAt: new Date() },
    { id: 'inv_part_005', name: 'Ignition Control Board', description: 'Universal ignition control board for furnaces.', sku: 'HVAC-ICB-UNIV', partNumber: 'ICM282A', modelNumber: 'ICM282', vendor: 'RE Michel', category: 'Control Boards', trade: 'HVAC', quantityOnHand: 8, reorderThreshold: 2, reorderQtyDefault: 4, warehouseLocation: 'Aisle 3, Bin 8', unitCost: 85.00, ourPrice: 210.00, truckLocations: [{technicianId: 'tech1', quantity: 1}], createdAt: new Date() },
  ] as InventoryItem[],
  technicians: [
    { id: 'tech1', name: 'John Doe', role: UserRole.Technician, color: 'hsl(210 80% 80%)' },
    { id: 'tech2', name: 'Jane Smith', role: UserRole.Technician, color: 'hsl(150 80% 80%)' },
    { id: 'tech3', name: 'Mike Johnson', role: UserRole.Technician, color: 'hsl(40 80% 80%)' },
    { id: 'tech4', name: 'Emily Brown', role: UserRole.Technician, color: 'hsl(300 80% 80%)' },
  ] as Technician[],
  customers: [
    {
      id: 'cust1',
      primaryContact: { firstName: 'Alice', lastName: 'Williams', email: 'alice@example.com', phone: '123-456-7890' },
      companyInfo: { name: 'Innovate Inc.', address: { street: '123 Tech Park', city: 'Silicon Valley', state: 'CA', zipCode: '94000' } },
      taxRegion: 'ca-sv',
      createdAt: new Date(),
      updatedAt: new Date(),
      hasOpenInvoices: true,
      smartTags: ['High Churn Risk'],
      recentTechnicians: [
          { id: 'tech1', name: 'John Doe' },
          { id: 'tech2', name: 'Jane Smith' },
      ],
    },
    {
      id: 'cust2',
      primaryContact: { firstName: 'Bob', lastName: 'Davis', email: 'bob@example.com', phone: '234-567-8901' },
      companyInfo: { name: 'Solutions Corp.', address: { street: '456 Business Blvd', city: 'Metropolis', state: 'IL', zipCode: '62960' } },
      taxRegion: 'il-metro',
      createdAt: new Date(),
      updatedAt: new Date(),
      hasOpenInvoices: true,
      smartTags: ['Recent Issue'],
       recentTechnicians: [
          { id: 'tech2', name: 'Jane Smith' },
          { id: 'tech3', name: 'Mike Johnson' },
          { id: 'tech4', name: 'Emily Brown' },
      ],
    },
      {
      id: 'cust3',
      primaryContact: { firstName: 'Charlie', lastName: 'Miller', email: 'charlie@example.com', phone: '345-678-9012' },
      companyInfo: { name: 'Gadgets & More', address: { street: '789 Market St', city: 'Gotham', state: 'NY', zipCode: '10001' } },
      taxRegion: 'ny-gotham',
      createdAt: new Date(),
      updatedAt: new Date(),
      hasOpenInvoices: false,
      smartTags: [],
       recentTechnicians: [
          { id: 'tech1', name: 'John Doe' },
      ],
    },
  ] as Customer[],
  jobs: [
    {
      id: 'job1',
      customerId: 'cust1',
      technicianId: 'tech1',
      schedule: { start: new Date(getDay(1).setHours(9, 0, 0, 0)), end: new Date(getDay(1).setHours(11, 0, 0, 0)) },
      status: 'complete',
      title: 'HVAC Tune-up',
      description: 'Annual maintenance for HVAC system.',
      details: { serviceType: 'HVAC Maintenance' },
      createdAt: new Date(),
      updatedAt: new Date(),
      duration: 120,
      invoiceId: 'inv1',
    },
    {
      id: 'job2',
      customerId: 'cust2',
      technicianId: 'tech2',
      schedule: { start: new Date(getDay(1).setHours(10, 0, 0, 0)), end: new Date(getDay(1).setHours(12, 30, 0, 0)) },
      status: 'complete',
      title: 'Leaky Faucet',
      description: 'Repair leaky faucet in master bathroom.',
      details: { serviceType: 'Plumbing Repair' },
       createdAt: new Date(),
      updatedAt: new Date(),
      duration: 150,
      invoiceId: 'inv2',
    },
    {
      id: 'job3',
      customerId: 'cust1',
      technicianId: 'tech1',
      schedule: { start: new Date(getDay(2).setHours(13, 0, 0, 0)), end: new Date(getDay(2).setHours(14, 30, 0, 0)) },
      status: 'scheduled',
      title: 'Panel Upgrade',
      description: 'Upgrade main electrical panel.',
      details: { serviceType: 'Electrical Inspection' },
      createdAt: new Date(),
      updatedAt: new Date(),
      duration: 90,
    },
     {
      id: 'job4',
      customerId: 'cust3',
      technicianId: 'tech3',
      schedule: { start: new Date(getDay(3).setHours(8, 0, 0, 0)), end: new Date(getDay(3).setHours(10, 0, 0, 0)) },
      status: 'complete',
      title: 'Dishwasher Install',
      description: 'Install new Bosch dishwasher.',
      details: { serviceType: 'Appliance Installation' },
      createdAt: new Date(),
      updatedAt: new Date(),
      duration: 120,
      invoiceId: 'inv3',
    },
    {
      id: 'job5',
      customerId: 'cust2',
      technicianId: 'tech4',
      schedule: { start: new Date(getDay(4).setHours(14, 0, 0, 0)), end: new Date(getDay(4).setHours(16, 0, 0, 0)) },
      status: 'scheduled',
      title: 'Router Setup',
      description: 'Setup new office network router.',
      details: { serviceType: 'Network Setup' },
      createdAt: new Date(),
      updatedAt: new Date(),
      duration: 120,
    },
    {
      id: 'job6',
      customerId: 'cust3',
      technicianId: '',
      schedule: { start: new Date(), end: new Date() },
      status: 'unscheduled',
      title: 'Quote for AC',
      description: 'Provide quote for new AC unit.',
      details: { serviceType: 'Estimate' },
      createdAt: new Date(),
      updatedAt: new Date(),
      duration: 60,
    },
    {
      id: 'job7',
      customerId: 'cust1',
      technicianId: '',
      schedule: { start: new Date(), end: new Date() },
      status: 'unscheduled',
      title: 'Fix Garage Door',
      description: 'Garage door opener not working.',
      details: { serviceType: 'Repair' },
      createdAt: new Date(),
      updatedAt: new Date(),
      duration: 60,
    }
  ] as Job[],
  invoices: [
    {
      id: 'inv1',
      invoiceNumber: 'INV-2024-001',
      customerId: 'cust1',
      jobIds: ['job1'],
      title: 'HVAC Tune-up Invoice',
      status: 'refunded',
      issueDate: new Date('2024-07-10'),
      dueDate: new Date('2024-08-09'),
      lineItems: [
        { description: 'Annual HVAC Maintenance Service', quantity: 1, unitPrice: 250, origin: { type: 'estimate', id: 'est1' } },
        { description: 'Replacement 1-inch Filter', quantity: 2, unitPrice: 25, origin: { type: 'estimate', id: 'est1' } },
      ],
      subtotal: 300.00,
      taxes: [ { name: 'CA State Tax', amount: 24.00, rate: 0.08 }],
      total: 324.00,
      amountPaid: 324.00,
      balanceDue: 0.00,
      paymentTerms: 'Net 30',
      createdAt: new Date('2024-07-10'),
      linkedEstimateIds: ['est1'],
      quickbooksSync: {
        status: 'synced',
        lastSync: new Date(),
      },
      commission: [
        { technicianId: 'tech1', rate: 0.1, amount: 32.40, technicianName: 'John Doe' }
      ],
      auditLog: [
        { id: 'log1', timestamp: new Date('2024-07-10T11:05:00Z'), userId: 'tech1', userName: 'John Doe', action: 'Invoice Created', details: 'Created from job JOB-9611 after completion.' },
        { id: 'log2', timestamp: new Date('2024-07-10T14:20:00Z'), userId: 'admin1', userName: 'Admin User', action: 'Invoice Approved', details: 'Approved after review.' },
        { id: 'log3', timestamp: new Date('2024-07-10T14:21:00Z'), userId: 'system', userName: 'System', action: 'Email Sent', details: 'Sent to alice@example.com.' },
        { id: 'log4', timestamp: new Date('2024-07-15T09:15:00Z'), userId: 'cust1', userName: 'Alice Williams', action: 'Payment Received', details: 'Paid $324.00 via Credit Card.' },
        { id: 'log5', timestamp: new Date('2024-07-16T10:00:00Z'), userId: 'admin1', userName: 'Admin User', action: 'Refund Issued', details: 'Refunded $50.00 as goodwill gesture.' },
      ] as AuditLogEntry[],
    },
    {
      id: 'inv2',
      invoiceNumber: 'INV-2024-002',
      customerId: 'cust2',
      jobIds: ['job2'],
      title: 'Plumbing Repair Invoice',
      status: 'partially_paid',
      issueDate: new Date('2024-06-01'),
      dueDate: new Date('2024-07-01'),
      lineItems: [
        { description: 'Emergency Callout Fee', quantity: 1, unitPrice: 150 },
        { description: 'Repair Kitchen Sink Leak', quantity: 1, unitPrice: 200, origin: { type: 'estimate', id: 'est2' } },
        { description: 'Replace Garbage Disposal', quantity: 1, unitPrice: 450, origin: { type: 'estimate', id: 'est2' } },
      ],
      subtotal: 800.00,
      taxes: [{ name: 'IL State Tax', amount: 64.00, rate: 0.08 }],
      total: 864.00,
      amountPaid: 400.00,
      balanceDue: 464.00,
      paymentTerms: 'Due on receipt',
      createdAt: new Date('2024-06-01'),
      linkedEstimateIds: ['est2'],
      linkedChangeOrderIds: ['co2'],
      quickbooksSync: {
        status: 'error',
        lastSync: new Date(new Date().getTime() - 24 * 60 * 60 * 1000), // 1 day ago
        error: 'Customer mapping failed: Customer "Solutions Corp." not found in QuickBooks.',
      },
       commission: [
        { technicianId: 'tech2', rate: 0.12, amount: 103.68, technicianName: 'Jane Smith' }
      ]
    },
    {
      id: 'inv3',
      invoiceNumber: 'INV-2024-003',
      customerId: 'cust3',
      jobIds: ['job4'],
      title: 'Appliance Install Invoice',
      status: 'sent',
      issueDate: new Date('2024-07-18'),
      dueDate: new Date('2024-08-17'),
       lineItems: [
        { description: 'Installation of customer-provided dishwasher', quantity: 1, unitPrice: 250 },
        { description: 'Haul away old appliance', quantity: 1, unitPrice: 50 },
      ],
      subtotal: 300.00,
      taxes: [{ name: 'NY State Tax', amount: 24.00, rate: 0.08 }],
      total: 324.00,
      amountPaid: 108.00,
      balanceDue: 216.00,
      paymentTerms: 'Net 30',
      createdAt: new Date('2024-07-18'),
      quickbooksSync: {
        status: 'pending',
      },
      paymentPlan: {
        type: 'manual',
        totalAmount: 324.00,
        schedule: [
            { amount: 108.00, dueDate: new Date('2024-07-18'), status: 'paid', paymentId: 'pay3' },
            { amount: 108.00, dueDate: new Date('2024-08-17'), status: 'pending' },
            { amount: 108.00, dueDate: new Date('2024-09-16'), status: 'pending' },
        ]
      },
       commission: [
        { technicianId: 'tech3', rate: 0.08, amount: 25.92, technicianName: 'Mike Johnson' }
      ]
    },
     {
      id: 'inv4',
      invoiceNumber: 'INV-2024-004',
      customerId: 'cust1',
      title: 'Quarterly Service Agreement',
      status: 'draft',
      issueDate: new Date('2024-07-20'),
      dueDate: new Date('2024-08-19'),
       lineItems: [
        { description: 'Q3 Service Agreement Maintenance', quantity: 1, unitPrice: 500, origin: { type: 'agreement', id: 'sa1' } },
      ],
      subtotal: 500.00,
      taxes: [{ name: 'CA State Tax', amount: 40.00, rate: 0.08 }],
      total: 540.00,
      amountPaid: 0.00,
      balanceDue: 540.00,
      paymentTerms: 'Net 30',
      createdAt: new Date('2024-07-20'),
      linkedServiceAgreementId: 'sa1'
    },
  ] as Invoice[],
  equipment: [
      {
          id: 'equip1',
          name: 'Fluke 87V Multimeter',
          technicianId: 'tech1',
          customerId: 'cust1',
          make: 'Fluke',
          model: '87V',
          serial: 'SN12345ABC',
          notes: 'Primary diagnostic tool for John Doe.',
          purchaseDate: new Date('2022-01-15'),
          purchasePrice: 450,
          warrantyEndDate: new Date('2025-01-14'),
          condition: 'good',
          lastInspectionDate: new Date('2024-01-10'),
          installedDate: new Date('2021-06-15'),
      },
      {
          id: 'equip2',
          name: 'Milwaukee M18 Hammer Drill',
          technicianId: 'tech2',
          customerId: 'cust1',
          make: 'Milwaukee',
          model: '2804-20',
          serial: 'SN67890DEF',
          notes: 'Heavy-duty drill.',
          purchaseDate: new Date('2023-05-20'),
          purchasePrice: 179,
          warrantyEndDate: new Date('2028-05-19'),
          condition: 'good',
          installedDate: new Date('2021-06-15'),
      },
       {
          id: 'equip3',
          name: 'Fieldpiece Manifold Gauge',
          technicianId: 'tech1',
          customerId: 'cust2',
          make: 'Fieldpiece',
          model: 'SM480V',
          serial: 'SN55511GHI',
          notes: 'Digital manifold for HVAC refrigerant work.',
          purchaseDate: new Date('2023-03-10'),
          purchasePrice: 750,
          warrantyEndDate: new Date('2025-03-09'),
          condition: 'new',
          installedDate: new Date('2022-01-20'),
      }
  ] as Equipment[],
  estimates: [
      {
          id: 'est1',
          estimateNumber: 'EST-001',
          title: 'Full HVAC System Replacement',
          customerId: 'cust1',
          jobId: 'job1',
          status: 'accepted',
          lineItems: [
              { description: 'Carrier Infinity Series AC Unit', quantity: 1, unitPrice: 4500 },
              { description: 'Carrier Infinity Series Furnace', quantity: 1, unitPrice: 3200 },
              { description: 'Labor and Installation', quantity: 16, unitPrice: 120 },
              { description: 'Ductwork Modification', quantity: 1, unitPrice: 800 },
          ],
          subtotal: 10420,
          discount: 500,
          taxes: [
            { name: "State Sales Tax", rate: 0.06, amount: 595.20 },
            { name: "County Sales Tax", rate: 0.01, amount: 99.20 }
          ],
          total: 10614.40,
          notes: 'This estimate includes a 5-year parts and labor warranty. A 10-year extended warranty is available.',
          gbbTier: {
              good: { description: "Basic replacement with a standard efficiency unit. Includes essential installation services.", price: 8500 },
              better: { description: "Upgraded, high-efficiency unit with a smart thermostat. Includes full system flush and balancing.", price: 10500 },
              best: { description: "Top-of-the-line, variable-speed system with zoning capabilities, advanced air purification, and a 10-year extended warranty.", price: 14000 },
          },
          createdBy: 'user_admin_01',
          createdAt: new Date('2024-07-10T10:00:00Z'),
          updatedAt: new Date('2024-07-11T14:30:00Z'),
      },
      {
          id: 'est2',
          estimateNumber: 'EST-002',
          title: 'Leaky Faucet Repair Options',
          customerId: 'cust2',
          jobId: 'job2',
          status: 'sent',
          lineItems: [
              { description: 'Faucet Cartridge Replacement', quantity: 1, unitPrice: 150 },
              { description: 'Labor', quantity: 1, unitPrice: 100 },
          ],
          subtotal: 250,
          discount: 0,
          taxes: [{ name: "Sales Tax", rate: 0.08, amount: 20 }],
          total: 270,
          notes: 'Repair of existing Moen faucet in master bathroom.',
          gbbTier: {
              good: { description: "Replace the cartridge in the existing faucet to stop the leak.", price: 270 },
              better: { description: "Replace the entire faucet with a new, mid-grade Delta model.", price: 450 },
              best: { description: "Upgrade to a premium Kohler faucet with a lifetime warranty and new supply lines.", price: 650 },
          },
          createdBy: 'tech1',
          createdAt: new Date('2024-07-15T09:00:00Z'),
          updatedAt: new Date('2024-07-15T09:30:00Z'),
      }
  ] as Estimate[],
  estimateTemplates: [
      {
          id: 'template-wh-install',
          title: 'Water Heater Installation',
          lineItems: [
              { description: 'Bradford White 50-Gallon Gas Water Heater', quantity: 1, unitPrice: 1200 },
              { description: 'Installation Labor', quantity: 4, unitPrice: 150 },
              { description: 'New Gas Line & Fittings', quantity: 1, unitPrice: 250 },
              { description: 'Haul Away Old Unit', quantity: 1, unitPrice: 75 },
          ],
          gbbTier: {
              good: { description: 'Install a standard 50-gallon gas water heater with a 6-year warranty. Includes basic code compliance and haul-away of the old unit.', price: 2200 },
              better: { description: 'Install a high-efficiency 50-gallon gas water heater with an 8-year warranty. Includes a new expansion tank and upgraded shut-off valve.', price: 2800 },
              best: { description: 'Install a premium, condensing tankless water heater for endless hot water and maximum energy savings. Includes a 12-year warranty and a whole-home plumbing inspection.', price: 4500 },
          }
      },
      {
          id: 'template-ac-diag',
          title: 'A/C System Diagnosis',
          lineItems: [
              { description: 'HVAC Diagnostic Fee', quantity: 1, unitPrice: 99 },
          ],
          gbbTier: {
              good: { description: 'Perform a full system diagnostic to identify the root cause of the issue. Provide a detailed report of findings and a quote for necessary repairs.', price: 99 },
              better: { description: 'Includes the diagnostic plus a basic refrigerant level check and top-off (up to 1lb of R-410A) and a standard filter replacement.', price: 249 },
              best: { description: 'Includes the diagnostic, refrigerant service, a new filter, and a comprehensive coil cleaning (indoor and outdoor) to restore system efficiency.', price: 499 },
          }
      },
      {
          id: 'template-repipe',
          title: 'Whole Home Repipe',
          lineItems: [
              { description: 'PEX-A Piping for Whole Home', quantity: 200, unitPrice: 5 },
              { description: 'Labor for Repipe', quantity: 40, unitPrice: 150 },
              { description: 'Drywall Repair & Patching', quantity: 1, unitPrice: 2500 },
              { description: 'Permits and Inspection', quantity: 1, unitPrice: 500 },
          ],
          gbbTier: {
              good: { description: 'Repipe the entire home with standard PEX-B tubing. Includes drywall access cuts and basic patching (not textured or painted).', price: 8000 },
              better: { description: 'Repipe using superior PEX-A tubing and install new quarter-turn shut-off valves at all fixtures. Includes professional drywall repair with texture matching.', price: 10500 },
              best: { description: 'Repipe with PEX-A, new valves, and include a new whole-home water filtration system and a pressure-reducing valve (PRV) for ultimate protection and water quality. Includes professional drywall repair, texture, and primer.', price: 13500 },
          }
      },
  ] as EstimateTemplate[],
  pricebookItems: [
    { id: 'pb_plumb_101', title: 'pull/reset with new supply line', description: 'pull/reset with new supply line', trade: 'Plumbing', price: 312, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_102', title: 'pull/reset with new wax only', description: 'pull/reset with new wax only', trade: 'Plumbing', price: 286, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_103', title: '*minor flange repair', description: '*minor flange repair', trade: 'Plumbing', price: 442, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_104', title: '*full flange repair', description: '*full flange repair', trade: 'Plumbing', price: 533, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_105', title: 'Install urinal wax ring', description: 'Install urinal wax ring', trade: 'Plumbing', price: 442, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_106', title: 'Install fill valve w new supply line', description: 'Install fill valve w new supply line', trade: 'Plumbing', price: 325, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_107', title: 'Install fill valve w new flush valve', description: 'Install fill valve w new flush valve', trade: 'Plumbing', price: 357.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_108', title: '*Add-on toilet flapper', description: '*Add-on toilet flapper', trade: 'Plumbing', price: 52, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_109', title: 'Install new talk to bowl bolts and gasket', description: 'Install new talk to bowl bolts and gasket', trade: 'Plumbing', price: 338, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_110', title: 'Install new flush valve, flapper, and bolts', description: 'Install new flush valve, flapper, and bolts', trade: 'Plumbing', price: 487.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_111', title: 'Install flush lever and flapper', description: 'Install flush lever and flapper', trade: 'Plumbing', price: 299, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_112', title: 'Complete Toilet Rebuild', description: 'Complete Toilet Rebuild', trade: 'Plumbing', price: 513.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_113', title: 'Install Customer Supplied Toilet (No Warranty)', description: 'Install Customer Supplied Toilet (No Warranty)', trade: 'Plumbing', price: 357.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_114', title: '*minor flange repair', description: '*minor flange repair', trade: 'Plumbing', price: 234, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_115', title: '*Angle stop and escutcheon', description: '*Angle stop and escutcheon', trade: 'Plumbing', price: 130, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_116', title: '*Fee for CLEAN SIDE TOILET', description: '*Fee for CLEAN SIDE TOILET', trade: 'Plumbing', price: 45.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_117', title: 'Install white, plastic, slow-closing toilet seat', description: 'Install white, plastic, slow-closing toilet seat', trade: 'Plumbing', price: 292.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_118', title: '*Add on toilet seat', description: '*Add on toilet seat', trade: 'Plumbing', price: 97.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_119', title: 'Auger Toilet with CLOSET AUGER', description: 'Auger Toilet with CLOSET AUGER', trade: 'Plumbing', price: 253.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_120', title: 'Auger by removing and resetting', description: 'Auger by removing and resetting', trade: 'Plumbing', price: 370.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_121', title: 'Install Angle stop for toilet with new supply line', description: 'Install Angle stop for toilet with new supply line', trade: 'Plumbing', price: 286, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_122', title: 'Install toilet flush lever', description: 'Install toilet flush lever', trade: 'Plumbing', price: 273, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_123', title: '*Add on toilet flush lever', description: '*Add on toilet flush lever', trade: 'Plumbing', price: 52, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_124', title: 'Replace Moen 1225 Cartridge', description: 'Replace Moen 1225 Cartridge', trade: 'Plumbing', price: 357.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_125', title: 'Replace Moen 1222 Cartridge', description: 'Replace Moen 1222 Cartridge', trade: 'Plumbing', price: 390, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_126', title: '*Upgrade Moen 1222 Heavy Duty', description: '*Upgrade Moen 1222 Heavy Duty', trade: 'Plumbing', price: 442, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_127', title: 'Replace Delta pressure balancing cartridge RP46074', description: 'Replace Delta pressure balancing cartridge RP46074', trade: 'Plumbing', price: 390, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_128', title: '*Replace Delta SEATS AND SPRINGS', description: '*Replace Delta SEATS AND SPRINGS', trade: 'Plumbing', price: 299, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_129', title: 'Replace Price Pfister SINGLE HANDLE CARTRIDGE', description: 'Replace Price Pfister SINGLE HANDLE CARTRIDGE', trade: 'Plumbing', price: 390, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_130', title: 'Replace Kohler 2-part cartridge and pressure balancing assembly', description: 'Replace Kohler 2-part cartridge and pressure balancing assembly', trade: 'Plumbing', price: 539.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_131', title: 'Install CUSTOMER SUPPLIED tub/shower/sink cartridge (NO WARRANTY)', description: 'Install CUSTOMER SUPPLIED tub/shower/sink cartridge (NO WARRANTY)', trade: 'Plumbing', price: 286, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_132', title: '*Add-On trim kit installation for tub/shower', description: '*Add-On trim kit installation for tub/shower', trade: 'Plumbing', price: 383.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_133', title: 'Install new tub/shower trim kit (basic, chrome)', description: 'Install new tub/shower trim kit (basic, chrome)', trade: 'Plumbing', price: 422.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_134', title: 'Replace single handle on tub/shower valve', description: 'Replace single handle on tub/shower valve', trade: 'Plumbing', price: 266.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_135', title: 'Replace 2 Handle Valve Stems', description: 'Replace 2 Handle Valve Stems', trade: 'Plumbing', price: 455, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_136', title: 'Replace 3 Handle Valve Stems', description: 'Replace 3 Handle Valve Stems', trade: 'Plumbing', price: 572, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_137', title: 'Install CUSTOMER SUPPLIED shower valve (basic install, NO WARRANTY)', description: 'Install CUSTOMER SUPPLIED shower valve (basic install, NO WARRANTY)', trade: 'Plumbing', price: 728, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_138', title: 'Install Moen Posi-Temp Shower valve with Chateau trim', description: 'Install Moen Posi-Temp Shower valve with Chateau trim', trade: 'Plumbing', price: 1020.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_139', title: 'Install Moen Posi-Temp Shower Valve Chateau trim with 3 HOLE CONVERSION PLATE', description: 'Install Moen Posi-Temp Shower Valve Chateau trim with 3 HOLE CONVERSION PLATE', trade: 'Plumbing', price: 1150.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_140', title: 'Replace "Toe Tip" and overflow plate (chrome)', description: 'Replace "Toe Tip" and overflow plate (chrome)', trade: 'Plumbing', price: 338, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_141', title: 'Replace "Toe Tip" DRAIN ONLY (chrome)', description: 'Replace "Toe Tip" DRAIN ONLY (chrome)', trade: 'Plumbing', price: 312, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_142', title: 'Tub Shroom silicone hair catcher', description: 'Tub Shroom silicone hair catcher', trade: 'Plumbing', price: 32.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_143', title: 'Replace water and overflow with new poly/ pvc / chrome', description: 'Replace water and overflow with new poly/ pvc / chrome', trade: 'Plumbing', price: 624, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_144', title: 'Replace waste and overflow AND PTRAP', description: 'Replace waste and overflow AND PTRAP', trade: 'Plumbing', price: 715, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_145', title: 'Remove Drum trap and install new PVC ptrap with waste and overflow', description: 'Remove Drum trap and install new PVC ptrap with waste and overflow', trade: 'Plumbing', price: 754, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_146', title: 'Replace tub spout with chrome', description: 'Replace tub spout with chrome', trade: 'Plumbing', price: 305.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_147', title: '*Add-on new tubspout', description: '*Add-on new tubspout', trade: 'Plumbing', price: 110.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_148', title: 'Install CUSTOMER SUPPLIED SHOWER HEAD (NO WARRANTY)', description: 'Install CUSTOMER SUPPLIED SHOWER HEAD (NO WARRANTY)', trade: 'Plumbing', price: 247, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_149', title: '*Add-On Customer SUPPLIED SHOWER HEAD (NO WARRANTY)', description: '*Add-On Customer SUPPLIED SHOWER HEAD (NO WARRANTY)', trade: 'Plumbing', price: 52, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_150', title: 'Install CUSTOMER SUPPLIED kitchen faucet (NO WARRANTY)', description: 'Install CUSTOMER SUPPLIED kitchen faucet (NO WARRANTY)', trade: 'Plumbing', price: 266.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_151', title: 'Install CUSTOMER SUPPLIED Electronic faucet (NO WARRANTY)', description: 'Install CUSTOMER SUPPLIED Electronic faucet (NO WARRANTY)', trade: 'Plumbing', price: 286, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_152', title: '*Add-On New braided SS Supply line each', description: '*Add-On New braided SS Supply line each', trade: 'Plumbing', price: 58.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_153', title: 'Install CUSTOMER SUPPLIED Garbage Disposal (NO WARRANTY)', description: 'Install CUSTOMER SUPPLIED Garbage Disposal (NO WARRANTY)', trade: 'Plumbing', price: 325, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_154', title: 'Install CUSTOMER SUPPLIED Dishwasher (NO WARRANTY)', description: 'Install CUSTOMER SUPPLIED Dishwasher (NO WARRANTY)', trade: 'Plumbing', price: 422.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_155', title: '*Add-On New braided SS Supply for dishwasher', description: '*Add-On New braided SS Supply for dishwasher', trade: 'Plumbing', price: 104, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_156', title: 'Install COPPER TEE w/ angle stop', description: 'Install COPPER TEE w/ angle stop', trade: 'Plumbing', price: 383.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_157', title: 'Install PEX TEE w/ angle stop', description: 'Install PEX TEE w/ angle stop', trade: 'Plumbing', price: 344.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_158', title: 'Install braided stainless supply line for refrigerator', description: 'Install braided stainless supply line for refrigerator', trade: 'Plumbing', price: 325, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_159', title: '*Add-On braided stainless supply line for refrigerator', description: '*Add-On braided stainless supply line for refrigerator', trade: 'Plumbing', price: 65, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_160', title: 'Replace continuous waste with proper sink drainage', description: 'Replace continuous waste with proper sink drainage', trade: 'Plumbing', price: 377, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_161', title: '1 basket strainer', description: '1 basket strainer', trade: 'Plumbing', price: 403, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_162', title: '2 basket strainer', description: '2 basket strainer', trade: 'Plumbing', price: 429, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_163', title: '*Add-On Ptrap or minor tubular slip joint repair', description: '*Add-On Ptrap or minor tubular slip joint repair', trade: 'Plumbing', price: 71.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_164', title: 'Re-Pipe ALL kitchen sink DRAINAGE with new basket strainers', description: 'Re-Pipe ALL kitchen sink DRAINAGE with new basket strainers', trade: 'Plumbing', price: 546, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_165', title: 'Lower waste arm and Re-Pipe all kichen sink drainage', description: 'Lower waste arm and Re-Pipe all kichen sink drainage', trade: 'Plumbing', price: 812.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_166', title: 'Remove Garbage Disposal and replace with basket strainer and minor piping', description: 'Remove Garbage Disposal and replace with basket strainer and minor piping', trade: 'Plumbing', price: 474.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_167', title: 'Install CUSTOMER SUPPLIED reverse osmosis system', description: 'Install CUSTOMER SUPPLIED reverse osmosis system', trade: 'Plumbing', price: 409.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_168', title: 'Auger kitchen sink up to 1hr', description: 'Auger kitchen sink up to 1hr', trade: 'Plumbing', price: 253.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_169', title: 'Manually remove blockage from garbage disposal', description: 'Manually remove blockage from garbage disposal', trade: 'Plumbing', price: 266.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_170', title: 'BADGER 5 - 1/2 HP DISPOSAL INSTALL', description: 'BADGER 5 - 1/2 HP DISPOSAL INSTALL', trade: 'Plumbing', price: 546, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_171', title: 'Evolution 3/4 HP DISPOSAL INSTALL', description: 'Evolution 3/4 HP DISPOSAL INSTALL', trade: 'Plumbing', price: 804.7, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_172', title: 'Install CUSTOMER SUPPLIED Water Heater (40/50Gal, NO UPGRADES, NO WARRANTY)', description: 'Install CUSTOMER SUPPLIED Water Heater (40/50Gal, NO UPGRADES, NO WARRANTY)', trade: 'Plumbing', price: 747.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_173', title: 'Bradford White NG or Electric 40gallon', description: 'Bradford White NG or Electric 40gallon', trade: 'Plumbing', price: 2145, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_174', title: 'Bradford White NG or Electric 50gallon', description: 'Bradford White NG or Electric 50gallon', trade: 'Plumbing', price: 2314, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_175', title: 'Bradford White NG or Electric 75gallon', description: 'Bradford White NG or Electric 75gallon', trade: 'Plumbing', price: 3835, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_176', title: 'Ball Valve', description: 'Ball Valve', trade: 'Plumbing', price: 299, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_177', title: '*Add-on Ball Valve', description: '*Add-on Ball Valve', trade: 'Plumbing', price: 78, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_178', title: 'Convert Saddle Valve to Angle Stop', description: 'Convert Saddle Valve to Angle Stop', trade: 'Plumbing', price: 292.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_179', title: '*Add-on Saddle Valve to Angle Stop', description: '*Add-on Saddle Valve to Angle Stop', trade: 'Plumbing', price: 117, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_180', title: 'Convert from Hard Pipe to Flex', description: 'Convert from Hard Pipe to Flex', trade: 'Plumbing', price: 312, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_181', title: '*Add-on Hard Pipe to Flex', description: '*Add-on Hard Pipe to Flex', trade: 'Plumbing', price: 143, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_182', title: 'Gas Hard Pipe to Flex Hose w Drip leg', description: 'Gas Hard Pipe to Flex Hose w Drip leg', trade: 'Plumbing', price: 364, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_183', title: '*Add-on Gas Hard Pipe to Flex Hose w Drip leg', description: '*Add-on Gas Hard Pipe to Flex Hose w Drip leg', trade: 'Plumbing', price: 182, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_184', title: 'Pan Installation', description: 'Pan Installation', trade: 'Plumbing', price: 325, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_185', title: '*Add-On Pan Installation', description: '*Add-On Pan Installation', trade: 'Plumbing', price: 78, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_186', title: '5 gallon Expansion Tank Installation', description: '5 gallon Expansion Tank Installation', trade: 'Plumbing', price: 546, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_187', title: '*Add-On 5 gallon Expansion Tank Installation', description: '*Add-On 5 gallon Expansion Tank Installation', trade: 'Plumbing', price: 305.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_188', title: 'Install new Gas Control Valve', description: 'Install new Gas Control Valve', trade: 'Plumbing', price: 676, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_189', title: 'Install CUSTOMER SUPPLIED Gas Control Valve (NO WARRANTY)', description: 'Install CUSTOMER SUPPLIED Gas Control Valve (NO WARRANTY)', trade: 'Plumbing', price: 455, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_190', title: 'Install new TP Valve', description: 'Install new TP Valve', trade: 'Plumbing', price: 383.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_191', title: 'Service TANK TYPE (vacuum out, clean thermocouple, test striker, clean filter, flush)', description: 'Service TANK TYPE (vacuum out, clean thermocouple, test striker, clean filter, flush)', trade: 'Plumbing', price: 312, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_192', title: 'TANKLESS FLUSH', description: 'TANKLESS FLUSH', trade: 'Plumbing', price: 409.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_193', title: 'Supply and Install brass laundry faucet', description: 'Supply and Install brass laundry faucet', trade: 'Plumbing', price: 572, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_194', title: 'Install New SS supply lines for washing machine', description: 'Install New SS supply lines for washing machine', trade: 'Plumbing', price: 312, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_195', title: 'Replace boiler drain with new SS supply (both)', description: 'Replace boiler drain with new SS supply (both)', trade: 'Plumbing', price: 500.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_196', title: 'Replace boiler drains', description: 'Replace boiler drains', trade: 'Plumbing', price: 455, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_197', title: 'Install 1/2in gas cock', description: 'Install 1/2in gas cock', trade: 'Plumbing', price: 331.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_198', title: 'Install flexible gas supply line', description: 'Install flexible gas supply line', trade: 'Plumbing', price: 370.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_199', title: 'Install new flexible supply with 1/2in gas cock', description: 'Install new flexible supply with 1/2in gas cock', trade: 'Plumbing', price: 481, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_200', title: 'Install 1/2in ball valve', description: 'Install 1/2in ball valve', trade: 'Plumbing', price: 390, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_201', title: 'install 3/4in ball valve', description: 'install 3/4in ball valve', trade: 'Plumbing', price: 455, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_202', title: 'Install 3/4in ball valve water cutoff on main', description: 'Install 3/4in ball valve water cutoff on main', trade: 'Plumbing', price: 500.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_203', title: 'Install 1in ball valve', description: 'Install 1in ball valve', trade: 'Plumbing', price: 520, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_204', title: 'Install 1in ball valve main water cutoff on main in box', description: 'Install 1in ball valve main water cutoff on main in box', trade: 'Plumbing', price: 624, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_205', title: 'Re-pipe water meter', description: 'Re-pipe water meter', trade: 'Plumbing', price: 624, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_206', title: 'Bypass and Remove Water Softener', description: 'Bypass and Remove Water Softener', trade: 'Plumbing', price: 520, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_207', title: 'Install Front Proof Silcock', description: 'Install Front Proof Silcock', trade: 'Plumbing', price: 383.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_208', title: 'Install Limited use Silcock', description: 'Install Limited use Silcock', trade: 'Plumbing', price: 591.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_209', title: 'Repair Frost Proof Silcock (if able)', description: 'Repair Frost Proof Silcock (if able)', trade: 'Plumbing', price: 305.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_210', title: 'Replace Single Handle faucet cartridge', description: 'Replace Single Handle faucet cartridge', trade: 'Plumbing', price: 396.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_211', title: 'Replace double handle valve stem/cartridge', description: 'Replace double handle valve stem/cartridge', trade: 'Plumbing', price: 448.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_212', title: 'Install CUSTOMER SUPPLIED 4in lavatory Faucet ( NO WARRANTY, CHARGE FOR SUPPLY LINES)', description: 'Install CUSTOMER SUPPLIED 4in lavatory Faucet ( NO WARRANTY, CHARGE FOR SUPPLY LINES)', trade: 'Plumbing', price: 305.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_213', title: 'Install CUSTOMER SUPPLIED 8in lavatory Faucet ( NO WARRANTY, CHARGE FOR SUPPLY LINES)', description: 'Install CUSTOMER SUPPLIED 8in lavatory Faucet ( NO WARRANTY, CHARGE FOR SUPPLY LINES)', trade: 'Plumbing', price: 331.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_214', title: 'Replace Angle Stope ONLY', description: 'Replace Angle Stope ONLY', trade: 'Plumbing', price: 286, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_215', title: 'Replace Angle Stop with supply line EACH', description: 'Replace Angle Stop with supply line EACH', trade: 'Plumbing', price: 312, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_216', title: 'Replace pop-up Assembly', description: 'Replace pop-up Assembly', trade: 'Plumbing', price: 331.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_217', title: 'Replace P- Trap', description: 'Replace P- Trap', trade: 'Plumbing', price: 318.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_218', title: '*Up-Charge for Pedestal sink', description: '*Up-Charge for Pedestal sink', trade: 'Plumbing', price: 104, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_219', title: 'Hydro-Jetting Srevice (up to 2 hours)', description: 'Hydro-Jetting Srevice (up to 2 hours)', trade: 'Plumbing', price: 877.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_220', title: '*Hydro-Jetting each additional hour after 2 hours', description: '*Hydro-Jetting each additional hour after 2 hours', trade: 'Plumbing', price: 325, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_221', title: 'Cable Sewer Main through accessible cleanout', description: 'Cable Sewer Main through accessible cleanout', trade: 'Plumbing', price: 331.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_222', title: 'Manually remove blockage from sewage pump', description: 'Manually remove blockage from sewage pump', trade: 'Plumbing', price: 325, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_223', title: 'Cable 2 - 4in drain through cleanout or floor drain', description: 'Cable 2 - 4in drain through cleanout or floor drain', trade: 'Plumbing', price: 305.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_224', title: 'Vacuum floor drain ONLY', description: 'Vacuum floor drain ONLY', trade: 'Plumbing', price: 182, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_225', title: 'Cable Toilet with Closet Auger', description: 'Cable Toilet with Closet Auger', trade: 'Plumbing', price: 253.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_226', title: 'Cable toilet by removing and resetting (NO MACHINE)', description: 'Cable toilet by removing and resetting (NO MACHINE)', trade: 'Plumbing', price: 370.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_227', title: 'Cable Sewer Main by pulling and resetting toilet up to 100ft', description: 'Cable Sewer Main by pulling and resetting toilet up to 100ft', trade: 'Plumbing', price: 526.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_228', title: 'Manually remove blockage from garbage disposal', description: 'Manually remove blockage from garbage disposal', trade: 'Plumbing', price: 214.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_229', title: 'Individual fixture drain cleaning with 1/4in cable machine', description: 'Individual fixture drain cleaning with 1/4in cable machine', trade: 'Plumbing', price: 266.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_230', title: 'Individual fixture drain cleaning with 1/2in cable machine', description: 'Individual fixture drain cleaning with 1/2in cable machine', trade: 'Plumbing', price: 344.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_231', title: 'Cable lav drain with Ptrap Replacement', description: 'Cable lav drain with Ptrap Replacement', trade: 'Plumbing', price: 357.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_232', title: 'Chemical Treatment', description: 'Chemical Treatment', trade: 'Plumbing', price: 338, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_233', title: '*Add on chemical treatment (root killer)', description: '*Add on chemical treatment (root killer)', trade: 'Plumbing', price: 156, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_234', title: '*Add on for Removal and replacement of BROKEN cleanout cap', description: '*Add on for Removal and replacement of BROKEN cleanout cap', trade: 'Plumbing', price: 117, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_235', title: 'PERFORM VIDEO CAMERA SEWER INSPECTION', description: 'PERFORM VIDEO CAMERA SEWER INSPECTION', trade: 'Plumbing', price: 338, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_236', title: '*Add on video camera sewer inspection', description: '*Add on video camera sewer inspection', trade: 'Plumbing', price: 156, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_237', title: '*Add on drain cleaning', description: '*Add on drain cleaning', trade: 'Plumbing', price: 169, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_238', title: '*Add on Roof Fee', description: '*Add on Roof Fee', trade: 'Plumbing', price: 65, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_239', title: 'Visual Inspection of Water and Sewer System - All visible piping - 1 hour', description: 'Visual Inspection of Water and Sewer System - All visible piping - 1 hour', trade: 'Plumbing', price: 292.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_240', title: 'Perform Smoke Test on Sewer System to locate Sewer gas leak', description: 'Perform Smoke Test on Sewer System to locate Sewer gas leak', trade: 'Plumbing', price: 975, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_241', title: 'Customer Provided single Filter Canister (Pre, Filter) Installation (NO WARRANTY)', description: 'Customer Provided single Filter Canister (Pre, Filter) Installation (NO WARRANTY)', trade: 'Plumbing', price: 1950, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_242', title: 'Customer Provided Double Canister (Pre, Filter, Conditioning) Installation (NO WARRANTY)', description: 'Customer Provided Double Canister (Pre, Filter, Conditioning) Installation (NO WARRANTY)', trade: 'Plumbing', price: 2405, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_243', title: 'Customer Provided Reverse Osmosis (NO WARRANTY)', description: 'Customer Provided Reverse Osmosis (NO WARRANTY)', trade: 'Plumbing', price: 338, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_244', title: '*Bypass Valve Upgrade', description: '*Bypass Valve Upgrade', trade: 'Plumbing', price: 325, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_245', title: '*Whole House UV add-on', description: '*Whole House UV add-on', trade: 'Plumbing', price: 1040, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_246', title: '1in RPZ installation in Yard with insulated rock', description: '1in RPZ installation in Yard with insulated rock', trade: 'Plumbing', price: 2210, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_247', title: '1in RPZ inatallation in garage with relief valve line run to outside', description: '1in RPZ inatallation in garage with relief valve line run to outside', trade: 'Plumbing', price: 2470, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_248', title: 'Backflow Testing ( city and filing fees will still be applied on top of testing fee)', description: 'Backflow Testing ( city and filing fees will still be applied on top of testing fee)', trade: 'Plumbing', price: 227.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_249', title: '160 lbs Sodium Salt', description: '160 lbs Sodium Salt', trade: 'Plumbing', price: 104, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_250', title: '160 lbs Potassium Salt', description: '160 lbs Potassium Salt', trade: 'Plumbing', price: 416, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_251', title: '*Countertop Hole drilling for RO faucet', description: '*Countertop Hole drilling for RO faucet', trade: 'Plumbing', price: 117, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_252', title: 'Install economy sump pump with new check valve', description: 'Install economy sump pump with new check valve', trade: 'Plumbing', price: 559, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_253', title: 'Install Liberty 1/3 HP sump pump with new check valve', description: 'Install Liberty 1/3 HP sump pump with new check valve', trade: 'Plumbing', price: 715, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_254', title: 'Install Liberty 1/2 HP sump pump with new check valve', description: 'Install Liberty 1/2 HP sump pump with new check valve', trade: 'Plumbing', price: 767, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_255', title: '*Add on fee for Liberty Brick sump pump pedestal', description: '*Add on fee for Liberty Brick sump pump pedestal', trade: 'Plumbing', price: 32.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_256', title: '*Add on fee for re-piping BBU with new primary installation', description: '*Add on fee for re-piping BBU with new primary installation', trade: 'Plumbing', price: 195, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_257', title: 'Install Liverty ejector pump with new check valve', description: 'Install Liverty ejector pump with new check valve', trade: 'Plumbing', price: 1098.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_258', title: 'Manually remove blockage from sewage pump', description: 'Manually remove blockage from sewage pump', trade: 'Plumbing', price: 507, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_259', title: 'Install economy sump pump in under-sink ssytem', description: 'Install economy sump pump in under-sink ssytem', trade: 'Plumbing', price: 754, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_260', title: 'Install Customer Supplied Sump Pump (NO WARRANTY)', description: 'Install Customer Supplied Sump Pump (NO WARRANTY)', trade: 'Plumbing', price: 455, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_261', title: 'Install customer Supplied BBU system (NO WARRANTY)', description: 'Install customer Supplied BBU system (NO WARRANTY)', trade: 'Plumbing', price: 689, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_262', title: 'Install Customer Supplied Sewage Pump (NO WARRANTY)', description: 'Install Customer Supplied Sewage Pump (NO WARRANTY)', trade: 'Plumbing', price: 578.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_263', title: 'Install 1 1/2in quiet close check valve', description: 'Install 1 1/2in quiet close check valve', trade: 'Plumbing', price: 305.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_264', title: 'Install 2in quet close check valve', description: 'Install 2in quet close check valve', trade: 'Plumbing', price: 435.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_265', title: 'Install vertical float switch, sump pump', description: 'Install vertical float switch, sump pump', trade: 'Plumbing', price: 344.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_266', title: 'Install vertical float switch, sewage pump', description: 'Install vertical float switch, sewage pump', trade: 'Plumbing', price: 552.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_267', title: 'Re-pipe sump pump discharge with new check valve (up to 10 ft)', description: 'Re-pipe sump pump discharge with new check valve (up to 10 ft)', trade: 'Plumbing', price: 474.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_268', title: 'Install new plastic ejector pit lid', description: 'Install new plastic ejector pit lid', trade: 'Plumbing', price: 292.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_269', title: 'Install new plastic sump pump lid', description: 'Install new plastic sump pump lid', trade: 'Plumbing', price: 136.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_270', title: 'Install Liberty 411 battery backup system (Basic Install)', description: 'Install Liberty 411 battery backup system (Basic Install)', trade: 'Plumbing', price: 1696.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_271', title: 'Install Liberty 442-10A battery backup system (Basic Install)', description: 'Install Liberty 442-10A battery backup system (Basic Install)', trade: 'Plumbing', price: 2314, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_272', title: 'Install Liberty 442-10A-EYE battery backup system (Basic Install)', description: 'Install Liberty 442-10A-EYE battery backup system (Basic Install)', trade: 'Plumbing', price: 2749.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_273', title: 'Install Zoeller Aquanot gel battery', description: 'Install Zoeller Aquanot gel battery', trade: 'Plumbing', price: 747.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_274', title: 'Install Basement Watchdog acid battery', description: 'Install Basement Watchdog acid battery', trade: 'Plumbing', price: 669.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_275', title: 'Service Fee - Normal Working Hours 7am - 5pm', description: 'Service Fee - Normal Working Hours 7am - 5pm', trade: 'Plumbing', price: 65, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_276', title: 'Emergency Fee (Monday - Saturday / 5pm - 7am)', description: 'Emergency Fee (Monday - Saturday / 5pm - 7am)', trade: 'Plumbing', price: 227.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_277', title: 'Emergency Fee (Sunday ALL DAY / NIGHT)', description: 'Emergency Fee (Sunday ALL DAY / NIGHT)', trade: 'Plumbing', price: 325, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_278', title: 'Leak Inspection (Not Responsible for drywall repairs)', description: 'Leak Inspection (Not Responsible for drywall repairs)', trade: 'Plumbing', price: 292.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_279', title: 'Water Pumping per 1/2 HR', description: 'Water Pumping per 1/2 HR', trade: 'Plumbing', price: 91, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_280', title: 'Realtor Letter', description: 'Realtor Letter', trade: 'Plumbing', price: 214.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_281', title: 'Limited Access Fee', description: 'Limited Access Fee', trade: 'Plumbing', price: 195, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_282', title: '1/2 Hour Written Inspection', description: '1/2 Hour Written Inspection', trade: 'Plumbing', price: 214.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_283', title: '1 Hour Written Inspection', description: '1 Hour Written Inspection', trade: 'Plumbing', price: 292.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_284', title: 'Pipe Thawing (NO WARRANTY) per hour', description: 'Pipe Thawing (NO WARRANTY) per hour', trade: 'Plumbing', price: 214.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_285', title: 'Credit Card Fee OVER $100', description: 'Credit Card Fee OVER $100', trade: 'Plumbing', price: 0.052, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_286', title: 'Hourly 0 - 4 hours', description: 'Hourly 0 - 4 hours', trade: 'Plumbing', price: 195, isCustom: true, createdAt: new Date() },
    { id: 'pb_plumb_287', title: 'Hourly 4 +', description: 'Hourly 4 +', trade: 'Plumbing', price: 162.5, isCustom: true, createdAt: new Date() },
    { id: 'pb_hvac_002', title: 'Capacitor Replacement', description: 'Replace dual-run capacitor for outdoor unit.', trade: 'HVAC', price: 280, estimatedLaborHours: 0.75, inventoryParts: [{ partId: 'inv_part_001', quantity: 1 }], isUrgent: true, createdAt: new Date() },
    { id: 'pb_plumb_001', title: 'Standard Faucet Install', description: 'Install customer-provided faucet.', trade: 'Plumbing', price: 250, estimatedLaborHours: 1.5, inventoryParts: [{ partId: 'inv_part_004', quantity: 1 }], createdAt: new Date() },
    { id: 'pb_plumb_002', title: 'Drain Clearing (Main Line)', description: 'Cable main sewer line up to 100ft.', trade: 'Plumbing', price: 450, isUrgent: true, createdAt: new Date() },
    { id: 'pb_plumb_003', title: 'Toilet Rebuild', description: 'Replace all internal tank components.', trade: 'Plumbing', price: 320, estimatedLaborHours: 1, createdAt: new Date() },
    { id: 'pb_hvac_001', title: 'AC Tune-up', description: 'Comprehensive cleaning and inspection of AC system.', trade: 'HVAC', price: 129, estimatedLaborHours: 1, inventoryParts: [], createdAt: new Date() },
    { id: 'pb_elec_001', title: 'GFCI Outlet Replacement', description: 'Replace a single GFCI electrical outlet.', trade: 'Electrical', price: 150, estimatedLaborHours: 0.5, inventoryParts: [{ partId: 'inv_part_003', quantity: 1 }], createdAt: new Date() },
    { id: 'pb_elec_002', title: 'Ceiling Fan Installation', description: 'Install customer-provided ceiling fan on existing brace.', trade: 'Electrical', price: 300, estimatedLaborHours: 2, createdAt: new Date() },
  ] as PricebookItem[],
};

    