

'use client';

import { useState, useMemo } from 'react';
import { useRouter } from 'next/navigation';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import type { ShoppingListItem, InventoryItem, PartRequest } from '@/lib/types';
import { useToast } from '@/hooks/use-toast';
import { FilePlus, Download } from 'lucide-react';
import { unparse } from 'papaparse';
import { format } from 'date-fns';
import { useRole } from '@/hooks/use-role';

interface ShoppingListProps {
    inventoryItems: InventoryItem[];
    partRequests: PartRequest[];
}

export function ShoppingList({ inventoryItems, partRequests }: ShoppingListProps) {
    const { toast } = useToast();
    const router = useRouter();
    const { role } = useRole();
    
    const shoppingList = useMemo(() => {
        const autoGenerated: ShoppingListItem[] = (inventoryItems || [])
            .filter(item => item.quantityOnHand <= item.reorderThreshold)
            .map(item => ({
                id: `auto_${item.id}`,
                itemId: item.id,
                itemName: item.name,
                quantityNeeded: item.reorderQtyDefault,
                reason: 'Reorder Threshold',
                trade: item.trade,
                vendor: item.vendor || 'N/A',
                destination: 'Warehouse',
            }));
        
        const fromRequests: ShoppingListItem[] = (partRequests || [])
            .filter(req => req.status === 'pending')
            .map(req => {
                const itemDetails = (inventoryItems || []).find(i => i.id === req.itemId || i.name === req.itemName);
                return {
                    id: req.id,
                    itemId: itemDetails?.id || `custom_${req.id}`,
                    itemName: req.itemName,
                    quantityNeeded: req.quantity,
                    reason: `Tech Request (${req.technicianName})`,
                    trade: itemDetails?.trade || 'General',
                    vendor: itemDetails?.vendor || 'N/A',
                    destination: req.technicianId,
                    requestId: req.id,
                }
            });

        // Use a map to consolidate requests for the same item ID
        const consolidatedMap = new Map<string, ShoppingListItem>();

        [...autoGenerated, ...fromRequests].forEach(item => {
            const existing = consolidatedMap.get(item.itemId);
            if (existing) {
                existing.quantityNeeded += item.quantityNeeded;
                if (!existing.reason?.includes(item.reason)) {
                    existing.reason += ` + ${item.reason}`;
                }
            } else {
                consolidatedMap.set(item.itemId, { ...item });
            }
        });

        return Array.from(consolidatedMap.values());
    }, [inventoryItems, partRequests]);

    const [selectedItems, setSelectedItems] = useState<Set<string>>(new Set());

    const handleSelectAll = (checked: boolean) => {
        if (checked) {
            setSelectedItems(new Set(shoppingList.map(item => item.id)));
        } else {
            setSelectedItems(new Set());
        }
    }
    
    const handleSelectRow = (itemId: string, checked: boolean) => {
        setSelectedItems(prev => {
            const newSet = new Set(prev);
            if (checked) newSet.add(itemId);
            else newSet.delete(itemId);
            return newSet;
        });
    }
    
    const handleExport = () => {
        const dataToExport = shoppingList.map(item => ({
            'Part Name': item.itemName,
            'SKU': inventoryItems.find(i => i.id === item.itemId)?.sku || 'N/A',
            'Quantity Needed': item.quantityNeeded,
            'Reason': item.reason,
            'Vendor': item.vendor,
        }));
        
        const csv = unparse(dataToExport);
        const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
        const link = document.createElement('a');
        const url = URL.createObjectURL(blob);
        link.setAttribute('href', url);
        link.setAttribute('download', `shopping-list-${format(new Date(), 'yyyy-MM-dd')}.csv`);
        link.style.visibility = 'hidden';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    }
    
    const handleCreatePO = () => {
        if(selectedItems.size === 0) {
            toast({ variant: 'destructive', title: 'No items selected', description: 'Please select items from the list to create a purchase order.' });
            return;
        }
        
        const itemsToOrder = shoppingList.filter(item => selectedItems.has(item.id));
        const queryParams = new URLSearchParams({
            items: encodeURIComponent(JSON.stringify(itemsToOrder.map(item => ({ 
                partId: item.itemId, 
                itemName: item.itemName,
                qty: item.quantityNeeded, 
                unitCost: inventoryItems.find(i => i.id === item.itemId)?.unitCost || 0 
            }))))
        }).toString();
        
        router.push(`/dashboard/purchase-orders/new?${queryParams}&role=${role}`);
    }

    return (
        <Card>
            <CardHeader className="flex flex-row items-center justify-between">
                <div>
                    <CardTitle>Master Shopping List</CardTitle>
                    <CardDescription>A consolidated list of all parts that need to be ordered.</CardDescription>
                </div>
                 <div className="flex items-center gap-2">
                    <Button variant="outline" onClick={handleExport}>
                        <Download className="mr-2 h-4 w-4" /> Export CSV
                    </Button>
                    <Button onClick={handleCreatePO} disabled={selectedItems.size === 0}>
                        <FilePlus className="mr-2 h-4 w-4" /> Create Purchase Order
                    </Button>
                </div>
            </CardHeader>
            <CardContent>
                <Table>
                    <TableHeader>
                        <TableRow>
                            <TableHead className="w-[50px]">
                                <Checkbox
                                    checked={selectedItems.size > 0 && selectedItems.size === shoppingList.length}
                                    onCheckedChange={handleSelectAll}
                                />
                            </TableHead>
                            <TableHead>Part Name</TableHead>
                            <TableHead>Qty</TableHead>
                            <TableHead>Reason</TableHead>
                            <TableHead>Trade</TableHead>
                            <TableHead>Vendor</TableHead>
                            <TableHead>Destination</TableHead>
                        </TableRow>
                    </TableHeader>
                    <TableBody>
                        {shoppingList.length > 0 ? shoppingList.map(item => (
                            <TableRow key={item.id}>
                                <TableCell>
                                    <Checkbox
                                        checked={selectedItems.has(item.id)}
                                        onCheckedChange={(checked) => handleSelectRow(item.id, !!checked)}
                                    />
                                </TableCell>
                                <TableCell className="font-medium">{item.itemName}</TableCell>
                                <TableCell className="font-bold text-lg">{item.quantityNeeded}</TableCell>
                                <TableCell>{item.reason}</TableCell>
                                <TableCell>{item.trade}</TableCell>
                                <TableCell>{item.vendor}</TableCell>
                                <TableCell>{item.destination}</TableCell>
                            </TableRow>
                        )) : (
                            <TableRow><TableCell colSpan={7} className="h-24 text-center">Your shopping list is empty.</TableCell></TableRow>
                        )}
                    </TableBody>
                </Table>
            </CardContent>
        </Card>
    );
}
